; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_pico_m]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
upload_protocol = esp-builtin
debug_tool = esp-builtin
debug_load_mode = modified
debug_server = 
	$PLATFORMIO_CORE_DIR/packages/tool-openocd-esp32/bin/openocd
	-f
	board/esp32s3-builtin.cfg
upload_speed = 921600
monitor_speed = 115200
monitor_filters = 
	esp32_exception_decoder
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_size = 8MB
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.partitions = partitions/custom_8mb_with_otadata.csv
build_unflags = 
	-std=gnu++2b
	-Wl,--no-warn-rwx-segments
build_flags = 
	-std=gnu++2a
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D CONFIG_TINYUSB_USB2UART=1
	-D CORE_DEBUG_LEVEL=3
	-D BOARD_HAS_PSRAM=1
	-D ESP32_S3_PICO_M=1
	-D PICO_BOARD_NAME=\"ESP32-S3-Pico-M\"
lib_deps = 
	adafruit/Adafruit PWM Servo Driver Library@^2.4.0
	https://github.com/espressif/Arduino-FOC.git#master
	adafruit/Adafruit MPU6050@^2.2.6
	teckel12/NewPing@^1.9.7
	janelia-arduino/PCA9685@^3.0.3
	francis-magallanes/CircularQueue@^1.1.0
platform_packages = 
	framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.0.2
	framework-arduinoespressif32-libs@https://github.com/espressif/arduino-esp32/releases/download/3.0.2/esp32-arduino-libs-3.0.2.zip
	toolchain-xtensa-esp32s3@8.4.0+2021r2-patch5
