; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico_w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
board_build.core = earlephilhower
framework = arduino
upload_protocol = picotool
monitor_speed = 115200
build_flags = 
	-D PICO_CYW43_ARCH_POLL=1
	-D PICO_BOARD_NAME=\"PicoW\"
	-D CYW43_LWIP=1
	-D CYW43_USE_WPA2=1
	-D LWIP_DNS=1
	-D LWIP_UDP=1
	-D LWIP_SNTP=1
	-D LWIP_NETIF_LINK_CALLBACK=1
	-D LWIP_NETIF_STATUS_CALLBACK=1
lib_deps = 
	adafruit/Adafruit PWM Servo Driver Library@^2.4.0
	askuric/Simple FOC@^2.3.4
	adafruit/Adafruit MPU6050@^2.2.6
	teckel12/NewPing@^1.9.7
	janelia-arduino/PCA9685@^3.0.3
