; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:pico]
; platform = raspberrypi
; board = pico
; framework = arduino
; board_build.core = earlephilhower
; upload_protocol = picotool # Or `cmsis-dap` if you're using a debugger, or `picoprobe`
; lib_deps =
;     # If you later add other external libraries, list them here

[env:pico_w]
platform = raspberrypi
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags =
    -D PICO_CYW43_ARCH_POLL=1
    -D PICO_BOARD_NAME=\"Pico W\"
    -D CYW43_LWIP=1
    -D CYW43_USE_WPA2=1
    -D LWIP_DNS=1
    -D LWIP_UDP=1
    -D LWIP_SNTP=1
    -D LWIP_NETIF_LINK_CALLBACK=1
    -D LWIP_NETIF_STATUS_CALLBACK=1
lib_deps =
    # No specific library dependencies needed beyond the framework for this setup
